apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      artifact-id:
        value: ${{ jobs.build.outputs.artifact-id }}
      version:
        value: ${{ jobs.build.outputs.version }}

jobs:
  build:
    outputs:
      artifact-id: db-artifact-${{ cloudbees.version }}
      version: ${{ cloudbees.version }}
    steps:
      - name: Check out
        uses: cloudbees-io/checkout@v2

      # Your build steps here

      - name: Register build artifact
        uses: cloudbees-io/register-build-artifacts@main
        with:
          artifact-metadata: |
            [
              {
                "name": "docker.io/mock/web",
                "version": "${{ cloudbees.version }}",
                "url": "docker.io/mock/web:${{ cloudbees.version }}",
                "type": "docker"
              }
            ]