apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      artifact-id:
        type: string
        required: true
      version:
        type: string
        required: true

jobs:
  deploy:
    steps:
      # Your deployment steps here

      - name: Register deployed artifact
        uses: cloudbees-io/register-deployed-artifact@v2
        with:
          artifact-id: ${{ inputs.artifact-id }}
          target-environment: ${{ inputs.environment }}